//Generated by WriteToAppconfig_ts - AppConfig.ts
import { ModelConfig } from "@/interfaces/ModelConfig";
//Generated by GetAllModelConfigImports
import { TaskConfig } from "@/utils/config/TaskConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { TaskCategoryConfig } from "@/utils/config/TaskCategoryConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { TaskIntervalConfig } from "@/utils/config/TaskIntervalConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { TagConfig } from "@/utils/config/TagConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { TaskTagConfig } from "@/utils/config/TaskTagConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { SubTaskConfig } from "@/utils/config/SubTaskConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { TaskTemplateConfig } from "@/utils/config/TaskTemplateConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { SubTaskTemplateConfig } from "@/utils/config/SubTaskTemplateConfig"; //Generated by GetModelConfigImports - GetModelConfigImports
import { TaskNoteConfig } from "@/utils/config/TaskNoteConfig"; //Generated by GetModelConfigImports - GetModelConfigImports

interface RelationshipInterface {
  seqModelRelationshipID: number;
  backendProjectID: number;
  leftModelID: number;
  rightModelID: number;
  relationship: string;
  leftForeignKey: string;
  rightForeignKey: string;
  declareInModel: number;
  through: number | null;
  isSimpleRelationship: boolean;
  fieldToBeInserted: string | null;
  excludeInForm: boolean;
  listName: string | null;
  excludeInRequiredList: boolean;
  includeAsDropzone: boolean;
  asListOnly: boolean;
  excludeInTable: boolean;
  includeAsLocalDropzone: boolean;
}

interface AppConfigType {
  appName: string;
  sidebarEnabled: boolean;
  appTitle: string;
  limit: number;
  sanitizedAppName: string;
  models: ModelConfig[];
  relationships: RelationshipInterface[];
}

export const AppConfig: AppConfigType = {
  appName: "postgres-todo",
  sidebarEnabled: true,
  appTitle: "To Do App",
  limit: 10,
  sanitizedAppName: "postgres_todo",
  models: [
    //Generated by GetAllSeqModelKeys
    TaskConfig,
    TaskCategoryConfig,
    TaskIntervalConfig,
    TagConfig,
    TaskTagConfig,
    SubTaskConfig,
    TaskTemplateConfig,
    SubTaskTemplateConfig,
    TaskNoteConfig,
  ],
  relationships: [
    //Generated by GetAllSeqModelRelationshipKeys
    {
      seqModelRelationshipID: 133,
      backendProjectID: 9,
      leftModelID: 85,
      rightModelID: 86,
      relationship: "1:M",
      leftForeignKey: "task_category_id",
      rightForeignKey: "id",
      declareInModel: 85,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: true,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 134,
      backendProjectID: 9,
      leftModelID: 85,
      rightModelID: 87,
      relationship: "1:M",
      leftForeignKey: "task_interval_id",
      rightForeignKey: "id",
      declareInModel: 85,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: true,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 135,
      backendProjectID: 9,
      leftModelID: 92,
      rightModelID: 91,
      relationship: "1:M",
      leftForeignKey: "task_template_id",
      rightForeignKey: "id",
      declareInModel: 92,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: false,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 136,
      backendProjectID: 9,
      leftModelID: 91,
      rightModelID: 86,
      relationship: "1:M",
      leftForeignKey: "task_category_id",
      rightForeignKey: "id",
      declareInModel: 91,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: true,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 137,
      backendProjectID: 9,
      leftModelID: 91,
      rightModelID: 87,
      relationship: "1:M",
      leftForeignKey: "task_interval_id",
      rightForeignKey: "id",
      declareInModel: 91,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: true,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 138,
      backendProjectID: 9,
      leftModelID: 90,
      rightModelID: 85,
      relationship: "1:M",
      leftForeignKey: "task_id",
      rightForeignKey: "id",
      declareInModel: 90,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: false,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 139,
      backendProjectID: 9,
      leftModelID: 85,
      rightModelID: 91,
      relationship: "1:M",
      leftForeignKey: "task_template_id",
      rightForeignKey: "id",
      declareInModel: 85,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: true,
      listName: null,
      excludeInRequiredList: true,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: true,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 140,
      backendProjectID: 9,
      leftModelID: 89,
      rightModelID: 85,
      relationship: "1:M",
      leftForeignKey: "task_id",
      rightForeignKey: "id",
      declareInModel: 89,
      through: 88,
      isSimpleRelationship: true,
      fieldToBeInserted: "tagID",
      excludeInForm: false,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 141,
      backendProjectID: 9,
      leftModelID: 89,
      rightModelID: 88,
      relationship: "1:M",
      leftForeignKey: "tag_id",
      rightForeignKey: "id",
      declareInModel: 89,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: true,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: false,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: false,
    },
    {
      seqModelRelationshipID: 142,
      backendProjectID: 9,
      leftModelID: 93,
      rightModelID: 85,
      relationship: "1:M",
      leftForeignKey: "task_id",
      rightForeignKey: "id",
      declareInModel: 93,
      through: null,
      isSimpleRelationship: false,
      fieldToBeInserted: null,
      excludeInForm: false,
      listName: null,
      excludeInRequiredList: false,
      includeAsDropzone: true,
      asListOnly: false,
      excludeInTable: false,
      includeAsLocalDropzone: true,
    },
  ],
};
