//Generated by WriteToAppconfig_ts - AppConfig.ts
import { ModelConfig } from "@/interfaces/ModelConfig";
//Generated by GetAllModelConfigImports
import { TaskConfig } from "@/utils/config/TaskConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { TaskCategoryConfig } from "@/utils/config/TaskCategoryConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { TaskIntervalConfig } from "@/utils/config/TaskIntervalConfig";//Generated by GetModelConfigImports - GetModelConfigImports


interface RelationshipInterface {
    seqModelRelationshipID: number;
backendProjectID: number;
leftModelID: number;
rightModelID: number;
relationship: string;
leftForeignKey: string;
rightForeignKey: string;
declareInModel: number;
through: number | null;
isSimpleRelationship: boolean;
fieldToBeInserted: string | null;
excludeInForm: boolean;
listName: string | null;
excludeInRequiredList: boolean;
includeAsDropzone: boolean;
asListOnly: boolean;
excludeInTable: boolean;
includeAsLocalDropzone: boolean;
}

interface AppConfigType {
    sidebarEnabled: boolean;
appTitle: string;
limit: number;
    models: ModelConfig[],
    relationships: RelationshipInterface[]
}

export const AppConfig: AppConfigType = {
    sidebarEnabled: false,
appTitle: "To Do App",
limit: 10,
    models: [//Generated by GetAllSeqModelKeys
TaskConfig,
TaskCategoryConfig,
TaskIntervalConfig,],
    relationships: [//Generated by GetAllSeqModelRelationshipKeys
{
seqModelRelationshipID: 120,
backendProjectID: 9,
leftModelID: 85,
rightModelID: 86,
relationship: "1:M",
leftForeignKey: "task_category_id",
rightForeignKey: "id",
declareInModel: 85,
through: null,
isSimpleRelationship: false,
fieldToBeInserted: null,
excludeInForm: true,
listName: null,
excludeInRequiredList: false,
includeAsDropzone: false,
asListOnly: false,
excludeInTable: false,
includeAsLocalDropzone: false,
},
{
seqModelRelationshipID: 121,
backendProjectID: 9,
leftModelID: 85,
rightModelID: 87,
relationship: "1:M",
leftForeignKey: "task_interval_id",
rightForeignKey: "id",
declareInModel: 85,
through: null,
isSimpleRelationship: false,
fieldToBeInserted: null,
excludeInForm: true,
listName: null,
excludeInRequiredList: false,
includeAsDropzone: false,
asListOnly: false,
excludeInTable: false,
includeAsLocalDropzone: false,
},],
}
