//Generated by WriteToBackendmodels_ts - backend-models.ts
//Generated by GetAllBackendModelImports
import { Task } from "@/models/TaskModel";//Generated by GetBackendModelImports - GetBackendModelImports
import { TaskCategory } from "@/models/TaskCategoryModel";//Generated by GetBackendModelImports - GetBackendModelImports
import { TaskInterval } from "@/models/TaskIntervalModel";//Generated by GetBackendModelImports - GetBackendModelImports

export const backendModels = {
  //Generated by GetAllBackedModelName
Task: Task,//Generated by GetBackedModelName - GetBackedModelName
TaskCategory: TaskCategory,//Generated by GetBackedModelName - GetBackedModelName
TaskInterval: TaskInterval,//Generated by GetBackedModelName - GetBackedModelName
};
