//Generated by WriteToGetmodeloptions_tsx - getModelOptions.tsx
//Generated by GetAllComponentImport
//Generated by GetComponentImport - GetComponentImport
import TaskForm from "@/components/tasks/TaskForm";
import TaskSingleColumn from "@/components/tasks/TaskSingleColumn";
//Generated by GetComponentImport - GetComponentImport
import TaskCategoryForm from "@/components/task-categories/TaskCategoryForm";
import TaskCategorySingleColumn from "@/components/task-categories/TaskCategorySingleColumn";
//Generated by GetComponentImport - GetComponentImport
import TaskIntervalForm from "@/components/task-intervals/TaskIntervalForm";
import TaskIntervalSingleColumn from "@/components/task-intervals/TaskIntervalSingleColumn";

export const getModelSingleColumns = () => {
  return {
    //Generated by GetAllModelSingleColumn
//Generated by GetModelSingleColumn - GetModelSingleColumn
Task: TaskSingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
TaskCategory: TaskCategorySingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
TaskInterval: TaskIntervalSingleColumn,
  };
};

export const getModelForms = () => {
  return {
    //Generated by GetAllModelForm
//Generated by GetModelForm - GetModelForm
Task: TaskForm,
//Generated by GetModelForm - GetModelForm
TaskCategory: TaskCategoryForm,
//Generated by GetModelForm - GetModelForm
TaskInterval: TaskIntervalForm,
  };
};
