//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { SubTaskModel } from "@/interfaces/SubTaskInterfaces";

const SubTaskSingleColumn = <T,>({ cell }: ModelSingleColumnProps<T>) => {
  const subTask = cell.row.original as SubTaskModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default SubTaskSingleColumn;
