//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import SubTaskFilterForm from "@/components/sub-tasks/SubTaskFilterForm";
import SubTaskTable from "@/components/sub-tasks/SubTaskTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { SubTaskModel } from "@/interfaces/SubTaskInterfaces";
import React from "react";

const SubTaskStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<SubTaskModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <SubTaskFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <SubTaskTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default SubTaskStateHolder;
