//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { TagModel } from "@/interfaces/TagInterfaces";

const TagSingleColumn = <T,>({
  cell,
}: ModelSingleColumnProps<T>) => {
  const tag = cell.row.original as TagModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default TagSingleColumn;
