//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import TagFilterForm from "@/components/tags/TagFilterForm";
import TagTable from "@/components/tags/TagTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { TagModel } from "@/interfaces/TagInterfaces";
import React from "react";

const TagStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<TagModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <TagFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <TagTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default TagStateHolder;
