//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import TaskNoteFilterForm from "@/components/task-notes/TaskNoteFilterForm";
import TaskNoteTable from "@/components/task-notes/TaskNoteTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { TaskNoteModel } from "@/interfaces/TaskNoteInterfaces";
import React from "react";

const TaskNoteStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<TaskNoteModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <TaskNoteFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <TaskNoteTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default TaskNoteStateHolder;
