//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { TaskTemplateModel } from "@/interfaces/TaskTemplateInterfaces";

const TaskTemplateSingleColumn = <T,>({
  cell,
}: ModelSingleColumnProps<T>) => {
  const taskTemplate = cell.row.original as TaskTemplateModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default TaskTemplateSingleColumn;
