//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { SubTaskTemplateModel } from "@/interfaces/SubTaskTemplateInterfaces";

const SubTaskTemplateSingleColumn = <T,>({
  cell,
}: ModelSingleColumnProps<T>) => {
  const subTaskTemplate = cell.row.original as SubTaskTemplateModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default SubTaskTemplateSingleColumn;
