"use client";
import SignOutButton from "@/components/header/SignOutButton";
import { Button } from "@/components/ui/Button";
import { useSessionStore } from "@/lib/supabase/useAuthSession";
import Link from "next/link";
import { usePathname } from "next/navigation";

//Generated by GeneratePageFile
import React, { useEffect, useState } from "react";

const SessionButton: React.FC = () => {
  const [mounted, setMounted] = useState(false);
  const session = useSessionStore((state) => state.session);
  const loading = useSessionStore((state) => state.loading);

  const pathname = usePathname();

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted || loading) {
    return null;
  }

  return session ? (
    <SignOutButton />
  ) : (
    <Button
      asChild
      className="rounded-full"
    >
      <Link href="/login">Sign-in</Link>
    </Button>
  );
};

export default SessionButton;
