//Generated by WriteToFooter_tsx - Footer.tsx
import React from "react";

const Footer: React.FC = () => {
  return (
    <div className="h-[50px] flex items-center justify-between max-w-screen-lg w-full px-4 text-xs select-none">
      <div>&copy; 2023 Pradascus. All rights reserved.</div>
    </div>
  );
};

export default Footer;
