//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { TaskCategoryModel } from "@/interfaces/TaskCategoryInterfaces";

const TaskCategorySingleColumn = <T,>({
  cell,
}: ModelSingleColumnProps<T>) => {
  const taskCategory = cell.row.original as TaskCategoryModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default TaskCategorySingleColumn;
