//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import TaskCategoryFilterForm from "@/components/task-categories/TaskCategoryFilterForm";
import TaskCategoryTable from "@/components/task-categories/TaskCategoryTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { TaskCategoryModel } from "@/interfaces/TaskCategoryInterfaces";
import React from "react";

const TaskCategoryStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<TaskCategoryModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <TaskCategoryFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <TaskCategoryTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default TaskCategoryStateHolder;
