//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { TaskIntervalModel } from "@/interfaces/TaskIntervalInterfaces";

const TaskIntervalSingleColumn = <T,>({
  cell,
}: ModelSingleColumnProps<T>) => {
  const taskInterval = cell.row.original as TaskIntervalModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default TaskIntervalSingleColumn;
