//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { TaskCategoryModel } from "@/interfaces/TaskCategoryInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { TaskIntervalModel } from "@/interfaces/TaskIntervalInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface TaskModel {
  //Generated by GetAllModelFieldTypeBySeqModel
taskCategoryID: number | string;//Generated by GetModelFieldType
taskIntervalID: number | string;//Generated by GetModelFieldType
id: number | string;//Generated by GetModelFieldType
description: string;//Generated by GetModelFieldType
taskTemplateID: number | string | null;//Generated by GetModelFieldType
date: string;//Generated by GetModelFieldType
targetDate: string;//Generated by GetModelFieldType
finishDateTime: string | null;//Generated by GetModelFieldType
isFinished: boolean;//Generated by GetModelFieldType
subTaskImported: boolean;//Generated by GetModelFieldType
  
  
  //Generated by GetAllRelatedRightModelInterface
TaskCategory: TaskCategoryModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
TaskInterval: TaskIntervalModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface TaskFormikShape extends Omit<TaskModel, "slug" | "createdAt" | "updatedAt" 
| "TaskCategory"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "TaskInterval"//Generated by GetRelatedRightModelName - GetRelatedRightModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface TaskFormikInitialValues {
  Tasks: TaskFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface TaskFormFormikInitialValues
  extends Omit<TaskFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface TaskUpdatePayload  {
  Tasks: Omit<TaskFormikShape, "touched">[];
  
}

export interface TaskDeletePayload {
  deletedTasks: string[] | number[];
}

export interface TaskSelectedPayload {
  selectedTasks: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface TaskFormUpdatePayload
  extends Omit<TaskFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface TaskFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
taskInterval: string;//Generated by GetThisFilterInterface
status: string;//Generated by GetThisFilterInterface
dateFrom: string; 
dateTo: string;//Generated by GetThisFilterInterface - GetThisBetweenFilterInterface
taskCategory: string;//Generated by GetThisFilterInterface
}

export interface TaskSearchParams
  extends ListQuery,
    Omit<TaskFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetTasksResponse {
  count: number;
  rows: TaskModel[];
  cursor: string;
}
