//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { TaskTagModel } from "@/interfaces/TaskTagInterfaces";

const TaskTagSingleColumn = <T,>({
  cell,
}: ModelSingleColumnProps<T>) => {
  const taskTag = cell.row.original as TaskTagModel;
  return <div className="flex gap-2">Edit Me Bruh!</div>;
};

export default TaskTagSingleColumn;
