//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import TaskTagFilterForm from "@/components/task-tags/TaskTagFilterForm";
import TaskTagTable from "@/components/task-tags/TaskTagTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { TaskTagModel } from "@/interfaces/TaskTagInterfaces";
import React from "react";

const TaskTagStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<TaskTagModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <TaskTagFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <TaskTagTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default TaskTagStateHolder;
